# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='direction',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
